### ISSUE TITLE
[BUG] Internal Error on Failed Kind Resolution

### ISSUE THREAD

**Issue by SchrodingerZhu** [koka-lang/koka#105]
```
module collections/imap;
type imap<a> {
    con Nil
    con Tip { k: int; v: a }
    con Bin { p: something-do-not-exist; m: int; l: do-not-exist<a>; r: do-not-exist<a> }
}
```
Instead of reporting an error on resolution, it yields an ` internal compiler error`:
```
*** internal compiler error: Kind.Infer.resolve data def: unknown type: something-do-not-exist
```

**Comment by daanx** [comment]
Thanks -- I'll look into it

**Comment by anfelor** [comment]
This is also triggered if the type variable has more than one character:
```
type typ<elem> {
    Typ(a : elem)
}
```
gives:
```
*** internal compiler error: Kind.Infer.resolve data def: unknown type: elem
```

Expected is either a error message indicating that type variables may only have one letter or no error (if this should be allowed).

**Comment by TimWhiting** [comment]
I believe this is now fixed. Please reopen, or create a new issue if this is not the case.
