### ISSUE TITLE
Unicode issue on interactive shell

### ISSUE THREAD

**Issue by anfelor** [koka-lang/koka#114]
There seems to be a problem with unicode support in the shell:
```
> "ü"
Cannot decode byte '\xfc': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
> val ue = "ü"
Cannot decode byte '\xfc': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
> ue
check  : interactive
  ^
((0), 1): error: identifier ue cannot be found
```
But when `val ue = "ü"` is defined in a loaded file:
```
check  : interactive
check  : interactive
linking: interactive
created: out/v2.0.14/gcc-debug/interactive
 
"\xFC"
```
FWIW Haskell's Text library is known to sometimes change behaviour based on environment variables like `LC_ALL`. So if you can't reproduce the issue try setting the locale env variables to `de_DE.utf8`.

**Comment by daanx** [comment]
Thanks -- I had trouble with the Haskell libraries before :-(  I will look into it.
