### ISSUE TITLE
A local-var can't be stored in a type

### ISSUE THREAD

**Issue by anfelor** [koka-lang/koka#116]
For example, this definition of a graph:
```
private struct graph<h> {
    nodes_ : local-var<h, vector<node>>
    num_edges_ : int
}
```
yields
```
graph.kk(49, 5): error: types do not match
  context      :     nodes_
  term         :     nodes_
  inferred type: vector<node>
  expected type: local-var<$h,vector<node>>
  because      : function returns values of different types
```
Is this expected behavior?

EDIT: One can use `ref` instead of `local-var` which makes updates of the vector a bit more cumbersome but works as expected.

**Comment by daanx** [comment]
Hi, good question/issue. I will try to document this more -- the `local-var` is an internal type used by `var` declarations; these are limited as their life-time is always limited to their lexical scope (checked through the `h` parameter). However, by limiting them we can give them the exact semantics of a `state` effect and create (in the future) more efficient implementations.

The `ref<h,a>` is the general type of references that are first-class and can have life times that exceed the lexical scope. An example of references is in the `samples/basic/garsia-wachs` example.

Hope this helps
