### ISSUE TITLE
Publish the Koka compiler somewhere

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#12]
PureScript is written in Haskell, and it uses [`bin-wrapper`](https://www.npmjs.com/package/bin-wrapper) to distribute pre-compiled Haskell binaries: [[link]](https://github.com/purescript-contrib/node-purescript-bin/blob/93e1697e8587243912b685e09f640b5e5fe6ce7a/lib/install.js)

This makes it possible to use `npm install purescript` to easily install PureScript.

A similar technique could be used for Koka.

**Comment by b-studios** [comment]
That's a very good idea -- we should really do that to ease the accessibility of the koka compiler.

**Comment by TimWhiting** [comment]
Koka now has easy installation via the vscode extension and also has a one line install command well documented on the website. I believe someone also maintains a brew package for MacOS, as well as a nix package. There is also a docker image, though it needs updating. I'll close this for now, but feel free to reopen, or create new issues if you feel there is a better publishing solution that is not covered.
