### ISSUE TITLE
Error message for wrong return type of effect handler isn't helpful

### ISSUE THREAD

**Issue by anfelor** [koka-lang/koka#126]
```
module test
import std/os/path

public fun main() {
    val p : path = appdir()
    return 0
}
```
With the latest Koka compiler, this fails with:
```
compile: test.kk
loading: std/core
loading: std/core/types
loading: std/core/hnd
loading: std/os/path
loading: std/text/parse
check  : test
add default effect for std/core/exn
(1, 0): error: types do not match
  context      : 
  term         : 
  inferred type: int
  expected type: ()
  because      : function returns values of different types
```
EDIT: Originally this was an issue about `appdir` which I suspected to be the culprit, but the error is that in case of an exception, main would return () and else an integer. That should be indicated in the error message.

**Comment by daanx** [comment]
ah, thanks. I see what is happening.

**Comment by TimWhiting** [comment]
I believe this is fixed now? The error message now references the main function.
