### ISSUE TITLE
Expanding names fails during loading

### ISSUE THREAD

**Issue by anfelor** [koka-lang/koka#127]
Place the following code in three files (a.kk, b.kk, c.kk):
```
module a
public alias node = int

module b
import a
private struct xyz {
    field : node
}

module c
import b
public fun main() {}
```
The first compilation works without error. On the second compilation:
```
compile: c.kk
loading: std/core
loading: std/core/types
loading: std/core/hnd
loading: b
Core.Parse.envQualify: unable to expand name: a/node: []
Core.Parse.envQualify: unable to expand name: a/node: []
Core.Parse.envQualify: unable to expand name: a/node: []
check  : c
linking: c
created: out/v2.0.14/gcc-debug/c
```
Interestingly, the error seems to have no impact at all, as the file can be loaded without a problem.

**Comment by daanx** [comment]
huh, strange error. Thanks for the report, I'll look into it.

**Comment by anfelor** [comment]
I can no longer reproduce this issue in Koka 3.1.1 using either mine or @philderbeast's minified example, so I assume it has been fixed.
