### ISSUE TITLE
assert(msg, cond) doesn't show message

### ISSUE THREAD

**Issue by anfelor** [koka-lang/koka#128]
```
public fun is-small(n : int) {
    assert("n smaller 10", n < 10)
    return n
}

public fun main() {
    with except throw-exn(e) {
        println("Exception!")
        return 0
    }
    return is-small(11)
}
```
fails with:
```
[1]    167457 segmentation fault (core dumped)  ./out/v2.0.14/gcc-debug/test
```
Expected would be either the use of the handler (`"Exception!"`) or a proper assertion error:
```
test: /home/user/test.kk: is-small: Assertion `n < 10' failed.
[1]    167128 abort (core dumped)  ./out/v2.0.14/gcc-debug/test 
```

I would assume that this problem is connected to the use of `unsafe-noexn` in the implementation of `assert`, since replacing `assert` with
```
    if(n < 10) unsafe-noexn {
        throw-exn(Exception("Hi!", ExnAssert))
    }
```
will never trigger the handler.

**Comment by daanx** [comment]
Ouch! The use of `assert` (and perhaps other invariants) is not worked out well at this point but I'll definitely fix this error; With the new evidence implementation the current assert implementation is indeed wrong. Thanks for the report

**Comment by daanx** [comment]
I think this is fixed now in the latest `dev` (a fresh binary release is coming soon)

**Comment by anfelor** [comment]
This example will now give the output:
```
fatal: assertion failed: n smaller 10
Aborted (core dumped)
```
