### ISSUE TITLE
Some functions don't allow effectful predicates

### ISSUE THREAD

**Issue by anfelor** [koka-lang/koka#130]
As can be seen in it's type signature: `fun find( xs : list<a>, pred : (a) -> bool ) : maybe<a>` doesn't allow an effect on `pred`. This is inconsistent with other functions in the library like `fun filter( xs : list<a>, pred : (a) -> e bool ) : e list<a>` that allow effects.

**Comment by anfelor** [comment]
This is also true for the following functions in core: `list.index-of`, `list.lookup`, `list.remove`, `string.count`, `fold-int`, `print-redirect`, `show-tuple`, `vector-init`.

**Comment by slightknack** [comment]
I'm new to Koka and this seems like an interesting project :)

So I see that these functions are defined in `lib/std/`, but they seem to rely on compiler magic. I'm interested in looking into resolving this issue - would someone mind pointing out where these functions are implemented on the compiler backend? Thanks!

**Comment by anfelor** [comment]
@slightknack  I think most of the functions are implemented in Koka code. I am not sure it is safe to touch those that are implemented in the backend (`print-redirect`, `vector-init`).

**Comment by anfelor** [comment]
I implemented this now as in my message of Feb 7

**Comment by anfelor** [comment]
@slightknack Are you still interested in Koka? There are a few other good projects and I can show you around if you want :)

**Comment by slightknack** [comment]
Yes, very much so! Rather than clogging up this issue, I'd imagine it'd be
best to chat via email ***@***.***) or on Discord
(slightknack#4221). Thanks!
