### ISSUE TITLE
[BUG] following code dows not compile

### ISSUE THREAD

**Issue by lian9998** [koka-lang/koka#140]
code and error message:

`type mynum
{ Int(i: int); Double(d: double) }

fun myadd(x:mynum, y:mynum) : exn mynum
{
    match(x)
    {
        Int(ix) -> match(y){Int(iy) -> Int(ix + iy)}
        Double(ix) -> match(y){Double(iy) -> Double(ix + iy)}
    }
}

fun mymult(x:mynum, y:int) : <exn,div> mynum
{
    if(y > 0) then
        myadd(x, mymult(x, (y - 1)))
    else
        match(x)
        {
            Int(_i) -> Int(1)
            Double (_d) -> Double(1.0)
        }
}

fun main()
{
    with handler { 
        except throw-exn(e) {
            println(e.message)
        }
    }
    match(myadd(Double(5.2), Double(5.2)))
    { Double(d) -> println(d) }
}`
cannot default to a value type due to mixed raw/regular fields: num
failure while running c:
  Backend.C.FromCore.genFunDefSig: not a function: (hw/.mlift387-mymult,hw/myadd)

**Comment by anfelor** [comment]
Hi, thanks for reporting this! We will track this bug in #151
