### ISSUE TITLE
is a possible to make the functions contravariant?

### ISSUE THREAD

**Issue by SchrodingerZhu** [koka-lang/koka#141]
Suppose I have the following functions:
```
extern create-with-hasher(h: a -> size_t): hashtable<a>{
  c inline "htable_with_hasher(#1, kk_context())"
}

fun create_int_table(): ndet hashtable<int> {
  val state = next-state();
  val hasher = fn (x: int) { myfunction-to-size_t(x) };
  create-with-hasher(hasher)
}
```

Here, what I want to have is that the `hasher` is of type `int -> size_t`, while  `create_with_hasher` takes
`a -> size_t`. In the backend, both type resolves to `kk_function_t` with a same signature. However, such usage is not allowed in Koka currently.

**Comment by SchrodingerZhu** [comment]
maybe the issue name is not appropriate.

But the actually behavior in Koka somehow looks like

fun f<a>(g: b -> size_t) : K<a>

Instead of

fun  f<a>(g: a -> size_t): K<a>

**Comment by anfelor** [comment]
I can't reproduce this in Koka 3.1.1. Please reopen this issue with an MWE if you still observe this behaviour.
