### ISSUE TITLE
Dot notation is like D's "unified function call syntax"

### ISSUE THREAD

**Issue by sgraf812** [koka-lang/koka#156]
I'm currently having a closer look at Koka and I really like what I'm seeing so far!

Rather than inciting a useful discussion on semantics, I want to split hairs about syntax: Dot notation (nice) seems very much like [D's "Unified Function Call Syntax"](https://tour.dlang.org/tour/en/gems/uniform-function-call-syntax-ufcs), which I've similarly grown to like. I'm saying that, because in [section 3.1.5 of the tour](https://koka-lang.github.io/koka/doc/book.html#sec-with), you write

> To the best of our knowledge, Koka was the first language to have generalized dot notation and trailing lambdas.

I'll agree about the trailing lambdas thing (although I imagine it's pretty similar to GHC 8.6's `-XBlockArguments`, but Koka probably predates it), not so much about the generalized dot notation. Maybe because Koka's take on dot notation is more general than D's and I'm not aware of that?

**Comment by daanx** [comment]
Ha, you are right -- thanks for the link; I never knew about this feature in the D language; really nicely designed language. 
I updated the docs :-)   dot notation is perhaps slightly more general as it is purely syntactical while in C (D) one  would need to first do a type check to know if one perhaps selects a field from a struct.
