### ISSUE TITLE
Typo in the Koka Programming Language page

### ISSUE THREAD

**Issue by kamoii** [koka-lang/koka#157]
Noticed this typo while reading the book. Should be `Red`.
![2021-03-05_23-35](https://user-images.githubusercontent.com/52167401/110130738-b36e7500-7e0c-11eb-9bcd-d1aa3133eca3.png)
Weird things is that the source of document(`doc/spec/tour.kk.md`) doesn't have this typo.

**Comment by anfelor** [comment]
Hi, this seems to have been fixed in the current version of the book. Thanks for reporting it!
