### ISSUE TITLE
Add Koka to https://github.com/kostya/benchmarks/

### ISSUE THREAD

**Issue by dumblob** [koka-lang/koka#168]
Koka is slowly reaching some usefulness levels, so I'd say it's time to add it to https://github.com/kostya/benchmarks/ (the most curated "generic" benchmark of programming languages as of now).

Could you make that happen?

**Comment by anfelor** [comment]
Hi, thanks for the link! We are currently using benchmarks similar to those of the Debian Benchmarksgame. However, we are always open to more benchmarks and, for example, a brainfuck implementation in Koka seems like a good first project! I'll be at ZuriHac this weekend and you can ping me if you need any pointers :)
