### ISSUE TITLE
A refererence to a list of integer can't be dereferenced correctly

### ISSUE THREAD

**Issue by kadu-v** [koka-lang/koka#174]
When the following code is run in REPL,  `[-578721382704613385]` that is a wrong value is printed.

```
fun test() : <st<h>, console> () {
    val r = ref([1, 2, 3])
    println(show(!r))
}
```

```
> test()
check  : interactive
check  : interactive
linking: interactive
created: out/v2.1.2/clang-debug/interactive
 
[-578721382704613385]
```

Environment:  
 Koka: v2.1.2  
 OS: macOS Big Sur

**Comment by daanx** [comment]
Thanks @kadu-v -- I remember this now and will look into it; scary bug

**Comment by daanx** [comment]
Hi @kadu-v ; I think it is fixed in the latest `dev` branch :-)   
Should be not too hard to build koka yourself; see [here](https://github.com/koka-lang/koka#build-from-source) and use `stack exec koka` to run it. Otherwise, I'll probably release a new version soonish.
