### ISSUE TITLE
Hardcoded colours on command line lead to unreadable code in light themes

### ISSUE THREAD

**Issue by wenkokke** [koka-lang/koka#190]
The Koka repl and command line utils use hardcoded colours, which makes their output quite difficult to read on light backgrounds. For instance:
![koka-cli](https://user-images.githubusercontent.com/3983973/131552379-90d5a64a-be80-46ba-85e9-8a572357dfd8.png)

**Comment by timmyjose** [comment]
I have almost the same colour mode as you, and I agree - it's unreadable, especially since it affects the inputs in the REPL as well.

**Comment by daanx** [comment]
Ah I will fix this with a nice dark&light theme. You can specify the colors on the command line but that is too cumbersome; until I fix this, you may work around it using --console=raw  (I think)

**Comment by daanx** [comment]
I pushed an initial fix to `dev` and `feature/borrow` making the default scheme work on both dark and light consoles. It'll be in the next release. This also supports `--color=none` to have no coloring at all.

**Comment by TimWhiting** [comment]
I'll close this as it seems this is fixed and acknowledged as so. Please open a new issue if for further issues with color.
