### ISSUE TITLE
Is it possible to specify the associativity of custom operators?

### ISSUE THREAD

**Issue by aaron-jack-manning** [koka-lang/koka#219]
For example if I have a curry function defined using the ? operator as follows:

```
fun (?) (f : a -> e z, a : a) : e z
    f (a)

fun (?) (f : (a, b) -> e z, a : a) : (f : b -> e z)
    fn (b) { f (a, b) }

fun (?) (f : (a, b, c) -> e z, a : a) : (f : (b, c) -> e z)
    fn (b, c) { f (a, b, c) }

...
```

When running the following code:

```
fun sum (a : int, b : int, c : int)
        a + b + c

val result = (sum ? 5 ? 6 ? 7)
```

I get the compiler error:

```
error: Ambigious non-associative operator (?) in a non-associative context
  hint: add parenthesis around the sub-expression to disambiguate
```

Is there a way in the function declaration to specify that it should be left associative?

**Comment by daanx** [comment]
Yes, look at `lib/std/core.kk` for examples. In your case, use:
```
infixl 30 (?)
```
makes it bind just under comparison operators like (==) etc.

**Comment by aaron-jack-manning** [comment]
Thank you for your reply. That was exactly what I was after.

**Comment by woojamon** [comment]
This no longer seems to be a valid solution. I couldn't find `infixl` in core.kk, and would like to specify the associativity of my operator.

**Comment by TimWhiting** [comment]
It should be. It has to be before any definitions though. It can be after imports though I think.

**Comment by woojamon** [comment]
Thank you! That works. The trick was that it has to be before any definitions.
