### ISSUE TITLE
For my syntax file, what are function-like blocks?

### ISSUE THREAD

**Issue by Alexey-T** [koka-lang/koka#229]
I m making lexer for CudaText.
I found in the samples, that function-like blocks are beginning with 3 keywords.
ie blocks with { } brackets. my app folds them.

```
fun
function
extern
```

is this complete list?

**Comment by daanx** [comment]
I don't fully understand the question. However, many keywords can be followed by a block. Also, a block usually does not have braces but we use indentation most of the time ([the layout rule](https://koka-lang.github.io/koka/doc/book.html#sec-layout)).  That may be tricky for a lexical highlighter.  

Common keywords that have a block are `fun` (named function), `fn` (anonymous function), `match`, `handler`, `handle`, `extern`, and sometimes `then`,`else`.
