### ISSUE TITLE
manual import of std/num/ddouble required even when not used by my code

### ISSUE THREAD

**Issue by pmahoney** [koka-lang/koka#230]
Using koka 2.3.6 (or 2.3.2) on NixOS (can't currently compile 2.3.8 due to an updated haskell dependency).

I have this toy program that prints out a date in [RFC-822 format](https://datatracker.ietf.org/doc/html/rfc822#section-5) (e.g. HTTP protocol dates).

The compilation fails unless I import the two additional libraries (std/num/ddouble and std/time/timestamp) even though (I think) I'm not referencing types or functions from those directly.

I'm compiling with
```
$ koka --target=c prog.kk
```

(At some point in the past, a similar program compiled OK without the additional imports (perhaps version 2.1.4) but I'm not able to reproduce)

```koka
import std/time

// without importing this, compiler error:
//     add default effect for std/time/utc/utc
//     failure during code generation:
//       *** internal compiler error: Core.Parc.getDataDefInfo: cannot find type: std/num/ddouble/ddouble
import std/num/ddouble

// without importing this, compiler error:
//     add default effect for std/time/utc/utc
//     failure during code generation:
//       *** internal compiler error: Core.Parc.getDataDefInfo: cannot find type: std/time/timestamp/timestamp
import std/time/timestamp

fun short-name( wd : weekday ) : <total> string {
  match(wd) {
    Sun -> "Sun"
    Mon -> "Mon"
    Tue -> "Tue"
    Wed -> "Wed"
    Thu -> "Thu"
    Fri -> "Fri"
    Sat -> "Sat"
  }
}

fun month-short-name( m : int ) : <total> maybe<string> {
  match(m) {
    1 -> Just("Jan")
    2 -> Just("Feb")
    3 -> Just("Mar")
    4 -> Just("Apr")
    5 -> Just("May")
    6 -> Just("Jun")
    7 -> Just("Jul")
    8 -> Just("Aug")
    9 -> Just("Sep")
    10 -> Just("Oct")
    11 -> Just("Nov")
    12 -> Just("Dec")
    _ -> Nothing
  }
}

val tz-gmt : timezone = tz-utc( name = "GMT" )

val spc = " "

// Format the time in rfc822 format as an iovec. For example:
//
// Wed, 15 Nov 1995 06:25:24 GMT
fun rfc822-date( t : time = time-now(tz-gmt) ) : <ndet,utc> list<string> {
  [
    t.weekday.short-name, ",", spc,
    t.day.show, spc,
    t.month.month-short-name.default("?"), spc,
    t.year.show, spc,
    t.clock.show(0), spc,
    t.timezone.name,
  ]
}

fun main() {
  val d = rfc822-date().join("")
  print(d)
}
```

**Comment by daanx** [comment]
Ah thanks! This is due to inlining but should not happen; I'll investigate.

Btw. due to the new layout rule, you can also write the above without using braces, and without needing parenthesis on `match` or `if` expressions :-)

Also, `std/time/format` helps with formatting. I think you can do your example as:
```
println( t.format("ddd, D MMM YYYY HH:mm:ss ") ++ t.timezone.name )
```

(ah we should add a formatter for the timezone name as well)

**Comment by pmahoney** [comment]
> Btw. due to the new [layout rule](https://koka-lang.github.io/koka/doc/book.html#sec-layout), you can also write the above without using braces, and without needing parenthesis on `match` or `if` expressions :-)

Yeah I'm a little behind on some syntax updates :)

> 
> Also, `std/time/format` helps with formatting. I think you can do your example as:
> 
> ```
> println( t.format("ddd, D MMM YYYY HH:mm:ss ") ++ t.timezone.name )
> ```
> 

Ah, thanks. Didn't see that.

> ps2. can I fix the nixOS issue? did you `cabal update` (or `stack update`)? I guess this is perhaps not used on nixOS? Even though I do not currently use Nix I love the whole idea and concept, I used to be a PhD student with Eelco Dolstra and he wrote a fantastic thesis on the Nix fundamentals and it is amazing to see how far this got)

I'm pretty familiar with Nix, but not with the haskell packages machinery.  I just bumped the koka version in the existing nix package, and ran into a haskell dependency failure. Based on [https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/HACKING.md](haskell-modules/HACKING.md) I think the easiest route is just waiting a week or so until the packages get updated again.  (It's `isocline` which is at 1.0.5 in nixpkgs but >=1.0.6 in koka)

**Comment by daanx** [comment]
Nice. Btw. If you edit `stack.yaml` you can change isocline safely to 1.0.5 and it'll be fine. (just fixes an issue when running koka with /dev/null as input and output)

**Comment by daanx** [comment]
Fixed in the latest `dev` branch :-)
