### ISSUE TITLE
CudaText lexer for Koka

### ISSUE THREAD

**Issue by Alexey-T** [koka-lang/koka#239]
This is just an announce of a new lexer for CudaText (free editor). Lexer is ready, it can be installed from "plugins / Addon manager" as usual. You may give the feedback here.

Lexer does not support indentation based folding, is it a big deal?

You may close this topic if no feedback will be here.

**Comment by daanx** [comment]
Very cool! I will try it out soon :-)

**Comment by TimWhiting** [comment]
Closing this, since it is not really an issue, feel free to share on discord:  https://discord.gg/CEkHHnTqEv / or in github disccussions.
