### ISSUE TITLE
Ctrl+D should quit the REPL

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#25]
Right now, Ctrl+D displays the message `end of file` and does not quit the REPL. It is common practice for REPLs to quit when using Ctrl+D (at least on Linux).

However, it should only quit when the text prompt is empty. In other words:

```
> (Ctrl+D pressed)
```

In the above scenario, it should exit. However:

```
> some code or whatever (Ctrl+D pressed)
```

In the above scenario, it should *not* exit. Instead it should treat it as meaning "I am finished typing this expression, please parse/compile/execute it now".

**Comment by anfelor** [comment]
Hi, this was fixed by PR #108 :)
