### ISSUE TITLE
error: Type void is not defined in Koka 2.4.0

### ISSUE THREAD

**Issue by jacobdweightman** [koka-lang/koka#259]
I wrote this simple test program to throw and "catch" an exception, which works as expected:
```koka
fun foo() : exn ()
  throw("error message")

fun main() : console ()
  with ctl throw-exn(x)
    println("caught error: " ++ x.message)
  foo()
```

```bash
$ koka min.kk
$ ./.koka/v2.4.0/clang-debug/min
caught error: error message
```

I then decided that `foo` should never be resumed, and so I tried changing the return type to `void`, so that it is impossible to call the resumption from a handler. My new program looks like this:
```koka
fun foo() : exn void
  throw("error message")

fun main() : console ()
  with ctl throw-exn(x)
    println("caught error: " ++ x.message)
  foo()
``` 

But it fails to compile, with this error message:
```
min.kk(1,17): error: Type void is not defined
  hint: bind the variable using forall<void> ?
```

This seems very odd, since I'm able to use other types defined in `std/core/types.kk`, like `()`, `bool`, `maybe`, etc. I'm on MacOS 12.2.1 and installed Koka 2.4.0 yesterday via Homebrew. I'm able to work around this by defining `void` in my source.

**Comment by TimWhiting** [comment]
This is no longer publicly exported for whatever reason?
