### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#32]
This is super low priority, but eventually it would be great to have [WebAssembly](http://webassembly.org/) support.

WebAssembly is a statically-typed binary format for running code on the web. It can achieve close to native C performance.

WebAssembly is very low-level, at the same level as C: it only supports integers, floats, and top-level function pointers.

All memory must be allocated in a single large array, which behaves like virtual memory. There is no garbage collector, instead all memory must be manually allocated/freed.

There are various [planned features](http://webassembly.org/docs/future-features/) including thread support (threads are very unlikely to ever be implemented in JavaScript, so WebAssembly is the only way to access threads).

JavaScript code can import a WebAssembly module by using a regular ES6 `import`, and WebAssembly can import JavaScript code as well. WebAssembly is designed to integrate well into the JavaScript ecosystem.

Because it's so close to "the metal", and you have very fine control over everything (including memory management), and there's no overhead from the JS JIT, Koka should be significantly faster if it is compiled to WebAssembly.

C, C++, LLVM, and Rust can already compile to WebAssembly, with many other languages adding in support as well. There's also some [useful tools](https://github.com/WebAssembly/binaryen) which may help.

The biggest impediment to compiling Koka to WebAssembly is that [WebAssembly does not currently support garbage collection](https://github.com/WebAssembly/design/issues/1079), therefore Koka would have to implement its own custom garbage collector (or use an [existing garbage collector written for C/C++](https://en.wikipedia.org/wiki/Boehm_garbage_collector))

Eventually garbage collection will be supported in WebAssembly, and then it will be a good time to revisit this issue.

**Comment by b-studios** [comment]
This is related to this proposal: https://github.com/effect-handlers/wasm-effect-handlers

**Comment by itowlson** [comment]
Where does Koka-to-Wasm stand at the moment?  I did have a go at trying to compile the generated C to WASI via the WASI SDK Clang, and while trying to get that to work I saw some internal references to WASI in the C code.  But I couldn't get the incantations right to get the Caesar sample to work - I finally got it to compile but the module failed when run in Wasmtime.

It _seems_ (to this naive outsider) like the GC should no longer be an issue because you already have Koka compiling to C, which doesn't have a GC and is in theory compilable to Wasm.  But there's something in the build that is just not playing nicely with either Clang or Wasm/WASI.

Thanks!

**Comment by timjs** [comment]
I'm quite interested in the same question actually! With Perseus in place, it seems to me that Koka → C → Wasm should be a viable route, maybe modulo interaction with JavaScript API's. What's the reason it's not working yet? Do we need some runtime support? Some special flags to be generated? Something else?

**Comment by TimWhiting** [comment]
I believe wasm works now. Please open new issues with further feedback on the wasm support. Use the --target=wasm flag. Currently we use emscripten and wasmtime which you can install from here:

https://emscripten.org/docs/getting_started/downloads.html
https://wasmtime.dev/

I've also looked into WASI and Clang's WASI backend, and have gotten something to work, if you are interested I can give you a link to my fork, it's a bit out of date though. I'll have to talk to Daan about it at some point.
