### ISSUE TITLE
Incredibly huge memory usage when compiling

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#34]
When running this command:

```
koka --include="lib" --compile --library --outdir="build" --target="js" "toc.kk"
```

The Koka compiler very rapidly consumes 4 GiB of RAM.

**Comment by maelvalais** [comment]
Hi!

I reported the [very same issue](https://github.com/koka-lang/madoko/issues/10) when compiling madoko. Seems to be related to GHC 8 but I reproduced the same memory leak on GHC 7.10. 

The same issue has also been reported in [ghc-mod](https://github.com/DanielG/ghc-mod/issues/834) and a ticket has been [opened](https://ghc.haskell.org/trac/ghc/ticket/13110) in the official GHC issue tracker but it has not been updated for 2 months now.

**Comment by Pauan** [comment]
@maelvalais Thanks for the information. It does indeed sound like it's caused by GHC.

**Comment by TimWhiting** [comment]
This should be mostly fixed now. We use better strictness annotations, etc. Since it has been a long time since this issue was raised, I'm going to close it. If you run into more memory usage issues, let us know with more up to date reproducible examples.
