### ISSUE TITLE
[FEATURE] The ability to mark functions as "inline"

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#36]
It would be useful to be able to mark a function as `inline`, like this:

```koka
inline fun foo() {
  1 + 2
}
```

Now every time `foo()` is used, the compiler will replace it with `1 + 2`

This avoids the overhead of the function call, which provides a small speed increase for small functions.

It also enables many other optimizations (including stream fusion), and therefore it can significantly increase the speed of the program.

If the function is always called (and not used as a value), then the dead code eliminator can remove the function definition, which can reduce code size.

Functions with arguments can be inlined as nested `match` expressions, as follows:

```
inline fun foo(a) { a + a }
inline fun bar(a = 1) { a + a }
inline fun qux(a, b, c) { a + b + c }

foo(1)        # match (1) { a -> { a + a } }
bar()         # match (1) { a -> { a + a } }
bar(2)        # match (2) { a -> { a + a } }
qux(1, 2, 3)  # match (1) { a -> match (2) { b -> match (3) { c -> { a + b + c } } } }
```

Some care needs to be taken to ensure that local variables do not shadow outer variables:

```
val foo = 1

inline fun bar() { foo + foo }

fun qux() {
  val foo = 2
  bar()  # This needs to refer to the outer variable foo, not the local variable foo
}
```

An easy way to achieve this is to give every local variable a unique identifier which is guaranteed to not conflict with top-level identifiers.

If this feature is implemented, the compiler can use the generic inlining mechanism to solve issue #18, therefore this issue is a superset of issue #18

**Comment by TimWhiting** [comment]
This is implemented.
