### ISSUE TITLE
[BUG] Error when using identifier in pattern matching

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#37]
This code:

```
match (1) { a -> a }
```

Fails with this error:

```
Backend.JavaScript.FromCore.genMatch: no branch in match statement: [_x0]
```

**Comment by Pauan** [comment]
I did a lot of debugging, and I found the source of this bug:

1. Because a variable is not a constructor, [`conNamess` is empty](https://github.com/koka-lang/koka/blob/409bb98436eaa1b5a643f17c9705efde85cf120e/src/Core/AnalysisMatch.hs#L33).

2. So when it calls `visitBranches`, [the `cases` is empty](https://github.com/koka-lang/koka/blob/409bb98436eaa1b5a643f17c9705efde85cf120e/src/Core/AnalysisMatch.hs#L59).

3. This causes it to [print a warning](https://github.com/koka-lang/koka/blob/409bb98436eaa1b5a643f17c9705efde85cf120e/src/Core/AnalysisMatch.hs#L61) and [completely discards all of the branches](https://github.com/koka-lang/koka/blob/409bb98436eaa1b5a643f17c9705efde85cf120e/src/Core/AnalysisMatch.hs#L62), so the end result is that the `match` expression gets rewritten to `match (1) {}`

**Comment by b-studios** [comment]
I tried to reproduce the bug in the current version of Koka, but the above example successfully evaluates to `1`.
