### ISSUE TITLE
REPL crashes when using :t command

### ISSUE THREAD

**Issue by chtenb** [koka-lang/koka#400]
# Reproduction

1. Enter koka repl
2. Run `:t`
3. Press arrow up one or more times

The following error appears and the repl crashes
```
> :tAssertion failed: attr.x.color == term->attr.x.color || attr.x.color == IC_COLOR_NONE, file src/term.c, line 182
```

Reproduces on latest release as well as `dev`. Tested on Windows 11.

**Comment by daanx** [comment]
Apologies for the late reply -- this seems fixed in the latest koka. Thanks!
