### ISSUE TITLE
VS Code Extension Errors On Activation

### ISSUE THREAD

**Issue by han-tyumi** [koka-lang/koka#415]
I wanted to check out Koka, but I am unfortunately running into this issue when trying to run any Koka command.
The only thing that looks to be working is the syntax highlighting.

<img width="274" alt="image" src="https://github.com/koka-lang/koka/assets/13040345/7385747e-6644-4b88-9bf4-0bf8e4fb0582">

<img width="552" alt="image" src="https://github.com/koka-lang/koka/assets/13040345/00cb400d-6320-4198-aaf6-21023a127a67">

I'm on a M1 Mac with Koka installed manually through the curl script.
Had to run the install script with `sudo`.
I can run `koka` from the command line and it appears to be installed correctly.

<img width="505" alt="image" src="https://github.com/koka-lang/koka/assets/13040345/069534b8-98ef-474e-a01a-2e7e6c66ebde">

**Comment by TimWhiting** [comment]
Try opening a non empty folder / workspace with some Koka files in it. I might know where this is coming from.

**Comment by han-tyumi** [comment]
Aha! That does appear to be the issue.
Looks like the commands also work without Koka files within the open folder.

**Comment by TimWhiting** [comment]
I think I at least know how to fix it then so that it doesn't error out. It still probably won't fully start a language server, but at least the startup of the extension will not fail so that it can register the commands appropriately.
