### ISSUE TITLE
Index name issue

### ISSUE THREAD

**Issue by TimWhiting** [koka-lang/koka#436]
### Discussed in https://github.com/koka-lang/koka/discussions/434

<div type='discussions-op-text'>

<sup>Originally posted by **chtenb** January 16, 2024</sup>
Example code that demonstrates this error:

```koka
fun copy-and-replace-at(v : vector<a>, index : int, new : a) : exn vector<a>
  var result := v
  result[index] := new
  result
```

Full error:

```
repro.kk(3, 9): error: only functions or types with a copy constructor can be applied
 context      :         [index] := new
 term         :         [index]
 inferred type: int
```

What does this error mean exactly, and how would I write code like this without triggering this error?</div>

**Comment by daanx** [comment]
ha ha, that is a funny bug... if you rename `index` to say `ndex` it works :-)   I think I introduced this bug when streamlining identifiers recently and using the name `index` for the previous `[_]` method. I'll fix this asap.

**Comment by daanx** [comment]
Fixed now in `dev`. I may redesign this a bit more but perhaps first I'll update the spec with the new grammar changes to identifiers. Thanks again!
