### ISSUE TITLE
Checking stucks with implicit parameters on recursive data types

### ISSUE THREAD

**Issue by oxalica** [koka-lang/koka#446]
Run `show([])` in koka 3.0.1 REPL, it stucks on checking with 100% CPU, consuming more than 10GB memory, and I have to kill it.
Compiling a file with `fun foo() show([])` also yields the same result.

I guess it's guessing the implicit parameters and infinitely trying nested lists?

**Comment by TimWhiting** [comment]
This is already know and will be fixed in the next release. For now annotate the type #437
