### ISSUE TITLE
Syntax error for the type of functions that return functions

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#45]
Reproducible code in the REPL:

```
> fun foo(): () -> () { (fun() {}) }
                   ^
((2),18): error: function is applied to too many arguments
  context      :                  () { (fun() {}) }
  term         :                  ()
  inferred type: (()) -> ()
```

It's possible to workaround this issue by wrapping the type in parens:

```
fun foo(): (() -> ()) { (fun() {}) }
```

**Comment by b-studios** [comment]
The problem is probably in the definition of [`tatom`](https://github.com/koka-lang/koka/blob/8a248a489c1cd00dfd8624a209245d3a3a2f43b6/src/Syntax/Parse.hs#L1821-L1852) since it only allows a single `id`, not a function type.

**Comment by dhil** [comment]
This is not a bug. The ascribed "workaround" type is in fact the expected type, it is consistent with the inferred type:
```koka
> val f = fun() { (fun() {}) }
f : () -> (() -> ())
```
