### ISSUE TITLE
[FEATURE] Should allow for pattern matching on function arguments and val

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#46]
This code currently does not work:

```
fun foo((a, b)) {
  a + b
}

val (c, d) = (1, 2)
```

It would be nice to be able to pattern match on function arguments, and also with `val`

This would have the same behavior as `match`, including throwing exceptions when the match is not exhaustive.

**Comment by anfelor** [comment]
Pattern matching in function parameters is supported now! :partying_face:
