### ISSUE TITLE
Unresolved implicit parameter

### ISSUE THREAD

**Issue by TimWhiting** [koka-lang/koka#468]
### Discussed in https://github.com/koka-lang/koka/discussions/467

<div type='discussions-op-text'>

<sup>Originally posted by **woojamon** February  8, 2024</sup>
May I ask why the `show` function is not implicity resolved in the example below?

```koka
// main.kk

type myType
  MyCase(value:int)

fun show(result:error<myType>) : pure string
  match result
    Ok(m) -> "MyCase"
    Error(x) -> exn/show(x)

fun eq(left:error<myType>, right:error<myType>) : pure bool
  match (left,right)
    (Ok(_),Ok(_)) -> True
    (Error(l), Error(r)) -> l.message == r.message
    _ -> False

pub fun myFun(p1:a, p2:a, ?eq:(a,a) -> pure bool, ?show:a -> pure string) 
  "hello"

fun main()
  myFun(Ok(MyCase(1)),Ok(MyCase(2)))
```
> main.kk(19,36): error: cannot resolve implicit parameter
 context   :   myFun(Ok(MyCase(1)),Ok(MyCase(2)))
 parameter : ?show : (error<myType>) -> pure string
 candidates: ...
 hint      : add a (implicit) parameter to the function signature?</div>

This seems like a bug

**Comment by TimWhiting** [comment]
@woojamon
@daanx 

`?show=fn(x) x.show` works, but the above example should as well.

**Comment by woojamon** [comment]
Ok, I'll move some things to their own files. Thanks!

**Comment by woojamon** [comment]
Wait, why doesn't `eq` suffer the same problem then?

**Comment by TimWhiting** [comment]
It just happens to be typed checked prior to main, or is uniquely named.
