### ISSUE TITLE
What's the resume function?

### ISSUE THREAD

**Issue by zaoqi-unsafe** [koka-lang/koka#47]
What's the resume function?

**Comment by Pauan** [comment]
@zaoqi-unsafe The resume function is like a callback in JavaScript.

Let's say you are using some Node.js APIs in JavaScript:

```
function foo(cb) {
  fs.readFile("foo", function (err, data) {
    fs.writeFile("bar", data, cb);
  });
}
```

When the `readFile` function is finished, it will call the callback with the file contents.

Now consider this Koka code:

```
fun foo(): asyncx () {
  val data = read-file("foo")
  write-file("bar", data)
}
```

The Koka compiler will translate the above code into this JavaScript:

```
function read_file(path, resume) {
  // Do some stuff then call resume
}

function write_file(path, data, resume) {
  // Do some stuff then call resume
}

function foo(resume) {
  read_file("foo", function (data) {
    write_file("bar", data, resume);
  });
}
```

In other words, Koka automatically added in the callbacks for you.

When you write an effect handler, `resume` is the callback.

So if `read-file` never calls `resume`, then the `read-file` function will never return.

And if `read-file` does call `resume`, then the first argument to `resume` is the return value for `read-file`

**Comment by zaoqi-unsafe** [comment]
@Pauan
```
val state = handler(i) {
  return x -> x
  get()    -> resume(i,i)
  set(j)   -> resume(j,())
}
```

**Comment by Pauan** [comment]
@zaoqi-unsafe Handlers can have extra state (in this case `i`). When you call `resume`, the first argument is the new state, and the second argument is the return value.

So in this case `i` is the current state, and `resume(i,i)` keeps the current state, and `resume(j,())` sets the state to `j`

**Comment by b-studios** [comment]
Thanks for answering @Pauan -- I'll go ahead and close the issue.
