### ISSUE TITLE
[FEATURE] Iterators in the standard library

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#48]
The Koka papers mention iteration, but the standard library doesn't seem to define any iterators.

I propose that iteration be defined in the standard library, and all of the collection types should define iterators.

I also propose that a robust set of iterator combinators be defined, e.g. map, filter, take, drop, etc. These combinators should work on all iterators.

In addition, it should be easy to convert from one collection type to another, by converting from type Foo to an iterator, then from the iterator to type Bar:

```
// Convert from list to vector
vector( iter( [] ) )

// Convert from vector to list
list( iter( vector() ) )

// Convert from list to dict
dict( iter( [ ("foo", 1), ("bar", 2) ] ) )
```

This should replace the various ad-hoc conversion functions which currently exist.

**Comment by anfelor** [comment]
Hi, I have some trouble imagining how this could look. I'll be at ZuriHac this weekend, maybe you could show me a prototype there?

**Comment by cameron-martin** [comment]
I only started playing around with koka today, so this may have some unforseen issues. However, this how I imagine iterators could work (disregarding effect polymorphism):

```
effect yield<t>
  ctl yield(x : t) : ()

alias iterator<t> = () -> yield<t> ()

fun iter(xs : list<t>) : iterator<t>
  fn()
    xs.foreach fn(x) yield(x)

fun map(it: iterator<a>, f: (a) -> b) : iterator<b>
  fn()
    with ctl yield(x)
      resume(yield(f(x)))
    it()

fun filter(it: iterator<t>, f: (t) -> bool): iterator<t>
  fn()
    with ctl yield(x)
      if f(x) then yield(x)
      resume(())
    it()

fun collect(it: iterator<t>): div list<t>
  with ctl yield(x) Cons(x, resume(()))
  it()
  Nil

fun find(it: iterator<t>, f: (t) -> bool): div maybe<t>
  with ctl yield(x)
    if f(x) then Just(x)
    else resume(())
  it()
  Nothing

fun main()
  val list = [1, 2, 3, 4, 5, 6].iter.filter(is-even).map(fn(a) a * 2 ).collect
  println(list.show)

  val found = [1, 2, 3, 4, 5, 6].iter.find(is-even).unjust
  println(found.show)
```

**Comment by chtenb** [comment]
For something to be called an iterator, I think there should be a `next` function that pops the next item and the remaining iterator.
