### ISSUE TITLE
VSCode extension seems not to work

### ISSUE THREAD

**Issue by Gerhard-Piette** [koka-lang/koka#485]
Hi,

I installed the Koka VSCode plugin in VSCode 1.88 on Windows 10 and Arch Linux.

The installation of the Koka plugin does not make VSCode ask to download the Koka compiler.
As indicated here:
[koka vscode does not install compiler](https://koka-lang.github.io/koka/doc/book.html#sec-install-with-the-vs-code-editor)

I get this error when I try to execute the command "Koka : Opensamples" in VSCode.
command 'koka.openSamples' not found

I get this error when I try to install the latest compiler in VSCode:
command 'koka.installCompiler' not found.

Then I have installed the Koka compiler manually on Arch linux with this command:
curl -sSL https://github.com/koka-lang/koka/releases/download/v3.1.1/install.sh | sh
From here:
https://github.com/koka-lang/koka/releases/tag/v3.1.1

Then I have stored the compiler location in the VSCode plugin settings.
Still the same problem.

**Comment by TimWhiting** [comment]
So there are a few issues here then. 
1. There is no installation prompt on plugin install
2. The plugin with a custom compiler location doesn't work?

As far as the first issue, I think I've seen this before, so I'll definitely look into that.
As far as the second issue, which VSCode plugin setting did you change? It should automatically find the compiler if it is on your path. I assume you are not using `koka.dev.developmentPath` which instructs it to look for a development clone of this repository (not an actual installed compiler), the `koka.languageServer.compiler` setting expects a full non-relative path to the executable including the executable name and extension (not just a path to the folder).

Are you having both issues on Windows, or just the first?

**Comment by TimWhiting** [comment]
I just found out why I was having trouble with the installation prompt on my system: Koka was configured to not disturb me with notifications for some odd reason. Try checking that? Click little bell in the bottom right and then follow through to the do-not-disturb configurations. Unintuitively, checking the box enables the notifications, while unchecking enables do-not-disturb. Depending on your settings, you might have to do this to all open windows.

<img width="489" alt="Screenshot 2024-04-06 at 9 47 43 PM" src="https://github.com/koka-lang/koka/assets/15617545/d47a3542-6444-462c-8f33-a6d9e28d91c6">

**Comment by Gerhard-Piette** [comment]
Hi,

thanks for the quick reply.
I am having the same problem on Windows 10 and Arch Linux.
I do not know about the **koka.dev.developmentPath** and **koka.languageServer.compiler.**
If it is important then it would be nice to have an obvious documentation.

This is a screenshot from my terminal on Arch Linux:
![Koka_terminal](https://github.com/koka-lang/koka/assets/71495761/1e64f71f-df42-4cd9-bfbe-8a8879d93aef)

These are my Koka  plugin settings in VSCode.
![Koka_plugin](https://github.com/koka-lang/koka/assets/71495761/8ebec310-8cff-488b-9a15-cf789e0bd131)

`There is no installation prompt on plugin install.`

Then it would be nice to have an updated documentation.
https://koka-lang.github.io/koka/doc/book.html#sec-install-with-the-vs-code-editor
Quote:
```
The easiest way to start with Koka is to use the excellent [VS Code editor](https://code.visualstudio.com/) and install the Koka extension. Go to the extension panel, search for Koka and install the official extension as shown on the right.

Installing the extension also prompts to install the latest Koka compiler on your platform (available for Windows x64, MacOS x64 and arm64, and Linux x64).
```

Besides :

It would be nice to have a uninstall command in addition to the install command.
This is available here: [https://github.com/koka-lang/koka/releases](https://github.com/koka-lang/koka/releases)
But not here: [https://koka-lang.github.io/koka/doc/book.html](https://koka-lang.github.io/koka/doc/book.html)

It would be nice to have an obvious link to the library on the front web page. I missed it before actively searching the web web site.

![Koka_library_link](https://github.com/koka-lang/koka/assets/71495761/b02cbc8e-3a44-4a5f-89aa-89cf4a1812e5)

**Comment by Gerhard-Piette** [comment]
I can not find the bell icon in my VSCode.

These are my notification settings.

![VSCode_notifications](https://github.com/koka-lang/koka/assets/71495761/9ba191cb-c344-4a48-b682-4a7441fcee2c)

Still no prompts from the Koka plugin. I uninstalled and installed the Koka plugin multiple times since unchecking the Zen mode.

**Comment by TimWhiting** [comment]
The bell icon is the only thing in the lower right corner of your window (not in the settings). For whatever reason even though I wasn't in Zen mode, my Koka notifications were muted individually.

I agree that the libraries should be more prominent on the webpage. (Created a new issue for that).

There should be an uninstall command in the VSCode command window when you start typing Koka. Try running that uninstall command, remove your manual `Koka > Language Server > Compiler` setting (this is what I was referring to as the `koka.languageServer.compiler` setting - that is what it corresponds to in the json settings file), run the clear all the global state command, and try the download and install via the command menu. 
<img width="589" alt="Screenshot 2024-04-07 at 8 29 37 AM" src="https://github.com/koka-lang/koka/assets/15617545/17198e10-01e4-4b09-9d9a-3c0ce70a8d1d">

Can you also open the VSCode `Help->Toggle Developer Tools` and post the logs that have anything to do with Koka?

**Comment by Gerhard-Piette** [comment]
Hi,

![VSCode_developer_tools](https://github.com/koka-lang/koka/assets/71495761/337ef828-dcb7-4ce4-8bf9-9add56c9eac8)

The problem is the same for all : command not found.

**Comment by TimWhiting** [comment]
Do you just have a single file open? I think the extension expects to have at least one workspace folder. Try opening a folder. If this is the issue, I know where to go to try to fix this.
