### ISSUE TITLE
How to uninstall Koka on Windows?

### ISSUE THREAD

**Issue by ice1000** [koka-lang/koka#499]
Is it enough to just hit `Uninstall.exe` for LLVM and delete `C:\Users\ice10\AppData\Local\koka`? I installed Koka via the `install.bat`, and I hit yes for installing clang and LLVM.

**Comment by TimWhiting** [comment]
You should be able to do `install.bat --uninstall`.

For llvm, yes you will probably have to uninstall separately.

**Comment by ice1000** [comment]
Thanks!
