### ISSUE TITLE
Add in support for arbitrary integers and also Uint64 / Int64

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#51]
There is a proposal for [adding BigInts to JavaScript](https://github.com/tc39/proposal-bigint). After the proposal is standardized, we should add some bindings to it.

In addition to supporting unlimited size integers, the proposal also gives some functions for creating fixed size integers (e.g. Int64 / Uint64). We should add in support for those as well.

**Comment by TimWhiting** [comment]
This is supported. See #388 for Daan's view on small ints / unsigned ints. Also read the accompanying paper if you are interested. I'll add a new issue for his proposal on a better bytes library, though I know it is close on his TODO list.
