### ISSUE TITLE
How would one declare mutable struct fields in Koka?

### ISSUE THREAD

**Issue by takanuva** [koka-lang/koka#54]
Is it possible to write structs (or any types for the matter) with mutable fields in Koka? How would one do that?

I understand I can use the state monad/effect for whole variables, but could I simulate mutating a field through a reference to the whole struct as one would do in an imperative language?

**Comment by dhil** [comment]
You can use reference cells to create mutable fields in a struct. For example consider a `person` structure with a mutable `age` field
```
struct person<h> = ( age : ref<h,int>
                   , name : string)
```
The age field is a reference to an integer on some heap `h`. The `person` structure is parameterised by the heap. 

As you note, another approach is to reference a whole structure, e.g.
```
struct person = ( age : int
                , name : string)

val p = ref(Person(42, "Koka")); {- type: forall<h>. (alloc<h>) ref<h,person> -}
```

**Comment by takanuva** [comment]
Is it possible to mutate a single field when the whole struct is inside the ref? Also, this seems to imply heap objects; could it be placed on the stack, or can the compiler optimize this (for, e.g., a C backend)?

**Comment by Pauan** [comment]
@takanuva No, if the entire struct is a ref, then you can only mutate the entire struct.

If you want to mutate a single field then that field has to be a ref.

Koka doesn't currently have a C target, only C# and JavaScript. I'm not sure whether it can be optimized to use the stack or not.
