### ISSUE TITLE
Formatting Error in last paragraph of "Tour of Koka -> Value Operations"

### ISSUE THREAD

**Issue by martihomssoler** [koka-lang/koka#541]
Hi there! I was just looking at the documentation of the language and found some kind of formatting error. Here is a screenshot of the issue.

![image](https://github.com/koka-lang/koka/assets/16923882/122fb669-fd7a-40c5-ba77-71e2a086dfef)

 I looked into the https://github.com/koka-lang/koka/blob/dev/doc/spec/tour.kk.md but the it seemed fine in there.

![image](https://github.com/koka-lang/koka/assets/16923882/f567fc67-2b64-42c2-8a60-ab3e8840ef8a)

Do not know if it is an issue on my end, just wanted to let you know.

**Comment by daanx** [comment]
Thanks! Fixed now.
