### ISSUE TITLE
Surprising behaviour of the type system.

### ISSUE THREAD

**Issue by phink** [koka-lang/koka#56]
Hello all,

I was playing with Koka and I was surprised by the following behaviours.
Consider the program below.

```
public module playground/pgm
effect free { ask () : a }

fun mtry(c) {
  handle(c) {
    ask() -> resume("abc")
  }
}

fun h () : free int { ask() }
```

As expected, the type of `h` is:

```
> :l playground/pgm.kk
> :t h 
() -> free int
```

Now, if we define `x` as follows: 

```
> val x = mtry{h()}
int
```
its type is `int` but its value "abc". 
```
> x
abc
```
I'm not familiar with algebraic effects nor with the Koka language but I think 
the previous example breaks the subject reduction property.
We can also use the following example to get a run-time type error.

```
> val y = mtry{h()} + 1
y : int
> y
Error: Invalid integer: abc ...
```

I'm not sure, but my guess is that the definition of `mtry` should not 
be accepted since the  type `a` escapes its scope. OCaml applies the same mechanism when
one wants to use the following GADT declaration.

```
# type t = Ask : 'a -> t;;
type t = Ask : 'a -> t
# let f = function Ask x -> x;;
Error: ... 
```

Ps: we have the same results with the dev branch.

**Comment by b-studios** [comment]
Hey, I know it is quite late for an answer but you are completely right. Actually, the handler 

```
handle(c) {
    ask() -> resume("abc")
  }
```

should have been rejected since `"abc"` is not an inhabitant of the universally quantified `a`. The bug appears to be fixed in the current version of Koka.

**Comment by phink** [comment]
Thanks for the answer.
