### ISSUE TITLE
nested comments

### ISSUE THREAD

**Issue by backtracking** [koka-lang/koka#594]
Nested comments are accepted in Koka source code, but then are copied verbatim in C source code, resulting in errors after the first closing `*/`. For instance, this Koka source code
```
/* a /* b */ fun main () 1 */
fun main() 42
```
results in the following syntax error:
```
test.h: In function ‘main’:
test.h:30:26: error: expected declaration specifiers before numeric constant
   30 | /* a /* b */ fun main () 1 */
      |                          ^
```

I'm using Koka version 3.1.2.

**Comment by daanx** [comment]
ah, darn. Will fix it soon :-)

**Comment by backtracking** [comment]
An easy fix would be to prefix the comments from Koka source with `//` in the C code.
(Or to remove them, of course, as this is in generated C code after all.)

**Comment by daanx** [comment]
Should be fixed now using your technique.
