### ISSUE TITLE
internal compiler error 

### ISSUE THREAD

**Issue by danr** [koka-lang/koka#60]
This innocent-looking program:

```
effect gen<a> {
  yield(item: a): ()
}

fun list<a,e>(program : () -> <gen<a>, e> ()): e list<a> {
  handle(program) {
    yield(x) -> Cons(x, resume(()))
    return _ -> Nil
  }
}
```

yields:

    *** internal compiler error: Type.Unify.labelName: label is not a constant

**Comment by b-studios** [comment]
Thanks for reporting this bug. Changing the type of `program` to be `() -> <gen<a>|e> ()` fixes the problem -- however this should really be fixed in the compiler.

**Comment by TimWhiting** [comment]
This should be fixed. Closing, but please reopen or create a new issue if you run into further problems.
