### ISSUE TITLE
internal error: Type.Infer.inferHandledEffect: cannot find handled effect in TVar

### ISSUE THREAD

**Issue by ov7a** [koka-lang/koka#613]
Given
```koka
import std/data/hashmap
import std/data/hash
import std/num/random

fun convert(lst: list<(string, string)>): random hash-map<string, string>
  with fun string/hash(k, s) string/hash(k)
  random/list/hash-map(lst)

fun main()
  val sample = [("key", "value")]
  convert(sample)
```
with std from [koka-community](https://github.com/koka-community/std/commit/851e687660899b1bb18c07157f8033dd9d771f54).

I get the following error:
```
test(1, 1): internal error: Type.Infer.inferHandledEffect: cannot find handled effect in TVar (TypeVar {typevarId = 16, typevarKind = KCon E, typevarFlavour = Meta})
CallStack (from HasCallStack):
  error, called at src/Common/Failure.hs:46:12 in koka-3.1.2-2NpoSf9Uv2JEsgjfT7jQ0Q:Common.Failure
  raise, called at src/Common/Failure.hs:32:5 in koka-3.1.2-2NpoSf9Uv2JEsgjfT7jQ0Q:Common.Failure
  failure, called at src/Type/Infer.hs:1264:46 in koka-3.1.2-2NpoSf9Uv2JEsgjfT7jQ0Q:Type.Infer

Failed to compile test.kk
```
Maybe it's a bug in the community std lib (because I expect hashes to "just work" without the overrides), but the error emitted points out that this is a compiler bug.

P.S. currently the workaround is to be very explicit
```koka
fun convert(lst: list<(string, string)>): random hash-map<string, string>
  fun hash(k: string, s: int64): int { string/hash(k) }
  random/list/hash-map(lst)
``` 
but I wonder what is the proper way to do this.

**Comment by TimWhiting** [comment]
Thanks for the report. This is already fixed on the latest development build of Koka. 

There are a few issues with this code:
1. Using `with fun` is syntax for creating an effect handler with one operation - I think this is where this error is coming from (on the dev branch this has the error: `not an effect operation: std/data/hash/string/hash.koka` instead, which is much better than a compiler crash.
2. The next issue is that local function declarations cannot use qualified names. (invalid syntax
qualified identifier) is what the compiler shows for me when I get rid of the `with` keyword.
3. Main implicitly prints the result, and `hash-map` does not have a `show` function. 

I think we ought to rename the community std to another name to better distinguish the fact that it is very experimental, and will likely change / and probably only a few parts will be integrated into Koka's `std` library. I'm thinking of splitting it up into a `test`, `datastructures`, `algorithms`, libraries etc, and making them more `official` community libraries as opposed to being targeted for `std` library integration. What do you think? I think we would be happy to contribute as much of them into the standard library as seems appropriate, but they likely need more time for maturing, and have started to get more expansive than a simple standard core library.

**Comment by ov7a** [comment]
@TimWhiting Thanks for the reply.

1. I agree it's better. It would be nice to add more details/suggestions, though. In the form you posted, it looks like as if it a file path and it's slightly confusing.
2. Yep, it's fair. However, `invalid syntax qualified identifier` is too brief IMO.
3. Yep, this behavior is surprising. I'd expect this effect to be explicit (do nothing by default). I discovered this after filing the issue.

Given that, it's still unclear to me how to use hash-map consistently. The `hash` parameter is implicit there. Ideally, I want it to "just work" given that `string/hash` is in scope. Unfortunately, that's not the case: by default, I get
```
type error: types do not match
  context      :   random/list/hash-map(lst)
  term         :                      
  inferred type: (string) -> int
  expected type: (string, int64) -> int
```
The next best option would be to define file-scoped `hash` function, since I obviously want to use the same hash function for creating and querying the hash map.Unfortunately, this does not work either:
```
fun hash(s: string, seed: int64): int { string/hash(s) }
```
```
test.kk(5, 5): type error: identifier hash cannot be resolved.
  context      :     hash
  inferred type: (s : string, seed : int64) -> int
  candidates   : hash                     : (s : string, seed : int64) -> int
                 std/data/hash/string/hash: (s : string, ?seed : int64) -> int
  hint         : give a type annotation or qualify the name?
```
```
fun hash(s: string, ?seed: int64): int { string/hash(s) }
```
```
test.kk(5, 5): type error: identifier hash cannot be resolved.
  context          :     hash
  inferred type    : (s : string, ?seed : int64) -> int
  candidates       : hash                     : (s : string, ?seed : int64) -> int
                     std/data/hash/string/hash: (s : string, ?seed : int64) -> int
  hint             : give a type annotation or qualify the name?
  missing implicits: ?seed
  hint             : ensure implicit functions are defined prior to functions that require them
```
The only way I found that works is to add `hash` function to the scope for each function that uses the hash map. This is weird. Am I missing something? 

P.S. sorry for the off-topic, but I want to illustrate that currently the error messages are not very helpful (and find better solution for my project of course). I guess this is expected given the status of the language, but I hope it can be improved.

**Comment by ov7a** [comment]
> I think we ought to rename the community std to another name to better distinguish the fact that it is very experimental, and will likely change / and probably only a few parts will be integrated into Koka's std library. I'm thinking of splitting it up into a test, datastructures, algorithms, libraries etc, and making them more official community libraries as opposed to being targeted for std library integration. What do you think? I think we would be happy to contribute as much of them into the standard library as seems appropriate, but they likely need more time for maturing, and have started to get more expansive than a simple standard core library.

I am all on board on renaming and splitting. However, this might be challenging without some package manager/package script/good way of handling the dependencies. I found it challenging to include the experimental std into the project smoothly. I explored the recommended way of using git modules, but I don't feel it's a good experience for users, and it has issues. I ended up writing a small script in bash to sparse-checkout the deps. At least there should be some basic pointers in the readme on usage instructions.

**Comment by TimWhiting** [comment]
Sorry about the poor state of documentation and introduction to the community libraries. At this point, it is still probably closer to an "enthusiast" rather than production-ready language, and the community / documentation reflects that to some degree. As such you should expect anything from the community libraries to be a WIP. Koka's `std` is more basic and less full featured, but more stable.

A better download strategy I feel is prerequisite to splitting the community std library. I'll probably investigate a stop-gap github based solution until we have an official package management solution. 

As far as the hash / hash-map module is concerned, I merged it in, but didn't develop it and haven't really used it, so I cannot speak to the developer experience there. That said, I took a quick look, and realized we added seed as an implicit parameter in the hash function which does not provide a good developer experience when using the collections. I think ideally the seed would be inferred as a thread-local seed, but there are some problems with Koka's inference of implicits I think that make that impossible currently. As such, I've made `seed` explicit for now, which allows the hash functions from the hash module to be used instead of redefining a hash. I've also added an example of usage in the `example` directory. FYI, I'm open to merging in any improvements / examples / documentation from users of the community libraries, and can make you a contributor if you are interested?

**Comment by ov7a** [comment]
Just to be clear: I didn’t meant anything negative. Sorry if it sounded that way. I understand the current state and I don’t expect much, just wanted to share the experience. The language has interesting ideas, and I hope it would have a great future.

> As such, I've made seed explicit for now, which allows the hash functions from the hash module to be used instead of redefining a hash. I've also added an example of usage in the example directory

This is awesome! I’ll try it later (not sure when though, I have limited time for thing kind of stuff)

> FYI, I'm open to merging in any improvements / examples / documentation from users of the community libraries, and can make you a contributor if you are interested?

No need to make me a contributor, but I can open a PR or two once I have better understaning of the lang and something decent to add:)

> A better download strategy I feel is prerequisite to splitting the community std library. I'll probably investigate a stop-gap github based solution until we have an official package management solution.

I agree.

**Comment by ov7a** [comment]
> This is awesome! I’ll try it later

Worked like a charm, thanks!
