### ISSUE TITLE
Chicken & egg problem: Koka depends on madoko, madoko depends on koka

### ISSUE THREAD

**Issue by michaeldg** [koka-lang/koka#63]
Hi,

When trying to compile madoko I found that it requires koka. When installing koka I found out that it depends on madoko.

I would guess madoko is needed to compile the docs. Perhaps an alternative could be to commit the koka documentation after compiling it.

Cheers,
MIchaël

**Comment by dhil** [comment]
I don't know which installation instructions you followed.

Make sure that you have a functioning installation of `ghc`, `cabal`, and `npm`. Koka depends on `alex` (a lexer generator), you can install it via cabal
```
cabal install alex
```
Thereafter you should clone this Koka repository and change directory to `koka`
```
git clone https://github.com/koka-lang/koka.git
cd koka
```
and then install the JavaScript dependencies via `npm`
```
npm install
```
Finally you should be able to build Koka using `jake`, simply type
```
jake
```

I will mark this issue as resolved. Feel free to reopen if the build still fails after following these instructions.
