### ISSUE TITLE
failed to read kki

### ISSUE THREAD

**Issue by Nymphium** [koka-lang/koka#83]
Koka version: commit ff10f07.

When I write an file `lib/std/ops.kk`
```
public module std/ops

public fun (+)(_, _) {
	"aaa"
}
```
 and  run `:l std/ops`, I succeed to load.

Then creating another file `lib/std/foo.kk` importing `std/opt`,
```
public import std/ops
```
 I get failed to load with the error message:
```
compile: lib/std/foo.kk
loading: std/core
loading: std/ops
out/lib/std_ops.kki(8,25): error: invalid syntax
 unexpected "("
 expecting ":"
```

This is `out/lib/std_ops.kki`.
```
module interface std/ops
/* This module defines standard operations that are always available.

   Some types and operations are required to be defined for the compiler
   to work correctly (i.e. types like `:int` or `:list`)
*/
import std/core = std/core = "";
fun (+) : forall<a,b> (_(3,16) : a, _(3,19) : b) -> std/core/string;
```

If removing `out/lib/std_ops.kki` file then I can load `lib/std/foo.kk`.
I doubt kki parser has something bug.

**Comment by anfelor** [comment]
Hi, thanks for reporting this! It seems to have been fixed since :)
