### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by jstnlef** [koka-lang/koka#84]
I'm curious why there has been less work on this project recently. Is it just a matter of time or lack of faith in the paradigm it's espousing?

**Comment by cmeiklejohn** [comment]
It's not dead; I was an intern at Microsoft Research this summer and did some work related to Koka.   I believe it's just a matter of time and prioritization. Don't worry!

**Comment by dhil** [comment]
> I'm curious why there has been less work on this project recently. Is it just a matter of time or lack of faith in the paradigm it's espousing?

The project is by no means dead. It does, however, currently have character of a research project, meaning it is vehicle for exploring new ideas.

 > Do you believe that a language which supports actors natively could also make use of algebraic effects or do they end up being solutions to the same concurrency problems?

A language with actors could most certainly benefit from having handlers for algebraic effects. They are orthogonal constructs, and in some sense they are not as actors are but an instance of effect handlers. So to answer your question: Yes, you can solve the same concurrency problems. 

From a programming perspective the neat thing about effect handlers is their generality and directness. They uniformly capture control idioms such as async/await, generators/iterators, ambient state, exceptions, etc as user-definable libraries. You can readily codify actors as a natural library using effect handlers.

**Comment by jstnlef** [comment]
I definitely appreciate the usefulness of algebraic effect handlers. It is quite an amazing abstraction. I guess getting more to the heart of my question, in creating a new language, do you feel it is useful for it to provide both a native actor mechanism AND an implementation of algebraic effects. To that end, is there something more fundamental about 1 vs the other? For example, Go style CSP can be implemented with actors pretty easily so it seems silly to have both. To me, effect handlers seem like a great way to structure non-lexical code execution flows but perhaps aren't necessarily useful for making the most of parallel processing provided by OS level threading. I'm curious what your thoughts are.

**Comment by patrickmn** [comment]
@jstnlef you should close this issue since the project is active
