### ISSUE TITLE
Strange compiler error(message)

### ISSUE THREAD

**Issue by aslakg** [koka-lang/koka#87]
The following (illtyped) program:

type tcterm<v, a> {
    Failure
}

effect chk {
    fun failure() : tcterm<v, a>
    fun lam(a : int) : v
}

val tchk = handler {
    failure() -> resume(Failure)
    lam(_) -> resume(Failure)
}

gives the error:
error: identifier .makeHandlerBranch0-x2 is undefined

If the , a are removed, we get a proper error from the typechecker.
Just thought I'd report it in case it uncovers a bug somewhere.

**Comment by anfelor** [comment]
Hi, thanks for reporting this! It seems to have been fixed during the past year. Feel free to reopen this issue if you have a similar error again :)
