### ISSUE TITLE
How to annotate?

### ISSUE THREAD

**Issue by aslakg** [koka-lang/koka#88]
This program:

effect greet {
    fun hello() : string
}

val tst = handler(counter : int) {
    hello() -> "Hello number " + show(counter)
}

fails with error: identifier show is ambiguous
hint: give a type annotation to the function parameters or arguments

Is this a bug in the type inferencer? Counter is annotated already as an int
Or is there another way I could annotate further?

**Comment by anfelor** [comment]
Hi, thanks for reporting this! It is based on a (now) old version of Koka though and local parameters have been replaced by local variables. Feel free to reopen this issue if something similar occurs in the current version :)
