### ISSUE TITLE
Missing text in koka book

### ISSUE THREAD

**Issue by mikesamuel** [koka-lang/koka#92]
https://github.com/koka-lang/koka/blob/master/doc/spec/overview.kk.md has

> Koka uses familiar curly-braces syntax where `//` starts a line comment. Functions are declared using the `fun` keyword.

The corresponding text at https://koka-lang.github.io/koka/doc/kokaspec.html#sec-hello-world reads

> Koka uses familiar curly-braces syntax where starts a line comment. Functions are declared using the `fun` keyword.

Note that the `//` does not show up in the book.

The affected HTML is

```html
<p class="p noindent">Koka uses familiar curly-braces syntax where <code class="koka"></code> starts a line
comment. Functions are declared using the <code class="koka"><span class="kw">fun</span></code> keyword.</p>
```

This may be an issue with the markdown&rArr;HTML converter used, or it might be an issue with the code highlighter.  Perhaps a line comment with no content and no trailing newline is not recognized as a complete token.

**Comment by daanx** [comment]
Thanks Mike -- I will fix this; actually, now that koka is transitioning to the new C backend there are lots of things that need updating and especially the documentation needs to be revamped; hopefully we get to it soon :-)

**Comment by mikesamuel** [comment]
@daanx, Please treat this as an FYI; don't hurry on my account.

**Comment by TimWhiting** [comment]
This looks solved?
