### ISSUE TITLE
Any plans to write a koka compiler in koka?

### ISSUE THREAD

**Issue by travis-leith** [koka-lang/koka#97]
Question in the title.

**Comment by mwilsoncoding** [comment]
See #40

**Comment by daanx** [comment]
:-) Yes, Koka is now functional enough to do this -- however, there are so many other priorities that it is not immediately on the list of things to do. It would be great but may take 6 months of work to do :-(   

Personally, my initial goal is to look within MS to see if we can apply Koka at a real service of program; now that the performance starts to be very good (see the Perceus paper) it can be a great language for "best performance without manual memory management" :-)
